In [1]:
import numpy as np

## Создание массива

#### В Python создается не массив, а список, чтобы список преобразовать в массив используется np.array()

In [2]:
my_list=[4,8,15,16,23,42]
array_from_list=np.array(my_list)
array_from_list

array([ 4,  8, 15, 16, 23, 42])

#### С полученным массивом можно производить различные операции, например, умножить каждый его элемент на 10

In [3]:
array_from_list*10

array([ 40,  80, 150, 160, 230, 420])

#### Создание массива из любого количества элементов, которые заполняются сами.

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Создать массив можно не только с нуля

In [5]:
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#### Вычислить длину массива - len()

In [6]:
len(np.arange(10,21))

11

#### Массив можно создать с определенным шагом

In [7]:
np.arange(10,21,3)

array([10, 13, 16, 19])

## Заполение массива

#### zeros() - заполняет массив нулями

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### ones() - заполняет массив единицами

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Создание многострочного массива



In [17]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Создание массива массивов (создается 5 массивов из 3х строчек и 2х столбцов)

In [16]:
np.zeros((5,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

#### Можем явно указывать тип элементов в массиве:

In [18]:
np.zeros(10, dtype='str')

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

## linspace

#### linspace позволяет расставить числовые значения на указанном интервале через равные промежутки, retstep  возвращает размер промежутков

In [10]:
start = 0
finish = 30
znachenia = 11
np.linspace(start,finish,znachenia, retstep = True)

(array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.]), 3.0)

## Вектор

#### Вектор - одномерный однострочный массив

In [19]:
my_vector = np.array([4,8,15,16,23,42])
my_vector

array([ 4,  8, 15, 16, 23, 42])

#### Можно присваивать любому элементу другие значение

In [20]:
my_vector[1] = 1
my_vector

array([ 4,  1, 15, 16, 23, 42])

#### shape() - позволяет разделить значения массива на определенное количество строк и столбцов

In [21]:
my_array = np.arange(35)
my_array.shape = (7,5)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

#### Теперь, если обратиться по индексу, то выведется не конкретной элемент, а строка

In [22]:
my_array[1]

array([5, 6, 7, 8, 9])

#### Чтобы обратиться к конкретному элементу, нужно указывать строку и столбец

In [23]:
row = 5
coloumn = 2
my_array[row,coloumn]

27

#### Вывести, являются ли четными элементы массива

In [24]:
my_vector = np.array([4,8,15,16,23,42])
mod_2 = (0 == my_vector%2)
mod_2

array([ True,  True, False,  True, False,  True])

#### Записываем в другой массив те элементы, которые подхолят под True

In [25]:
sub_array = my_vector[mod_2]
sub_array

array([ 4,  8, 16, 42])

#### Фильтрация в массиве

In [26]:
sub_array[sub_array>10]

array([16, 42])